remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Workout Log"
description: "An exercise app."
author:
  name: "John Jaramillo"
